apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "jkj"
  description: "lk"
  annotations:
    github.com/project-slug: blamdemo/gaskjgj
    backstage.io/techdocs-ref: url:https://github.com/blamdemo/gaskjgj
spec:
  type: documentation
  lifecycle: experimental
  owner: "h"
